version: '3.7'

services:
    mc:
        build:
            context: ./mc
        volumes:
            - ./.volumes/storage:/var/minecraft
            - ./.volumes/logs:/var/minecraft/logs
            - ./.volumes/backup:/var/backup
        ports:
            - '25565:25565'
